#!/usr/bin/env node
/**
 * dsh-new-plugin — scaffold a DSH dual-package plugin (Host + Client UI)
 * and wire every registration point automatically.
 *
 * Usage:  node scripts/new-plugin.mjs <slug>
 * Example: node scripts/new-plugin.mjs scheduler
 *
 * After running, execute the build triple:
 *   pnpm run build:lib:host
 *   npx tsdown --env.DSH_BUILD_FACE client
 *   pnpm run build:lib:client
 */
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')

// ── CLI ──────────────────────────────────────────────────────────────────────
const slug = process.argv[2]?.toLowerCase().replace(/[^a-z0-9-]/g, '')
if (!slug) { console.error('Usage: node scripts/new-plugin.mjs <slug>'); process.exit(1) }

const Pascal = slug.split('-').map(s => s[0].toUpperCase() + s.slice(1)).join('')
const camel = slug.split('-').map((s, i) => i === 0 ? s : s[0].toUpperCase() + s.slice(1)).join('')
const hostPkg = `@deepseek-ai/dsh-${slug}-host`
const clientPkg = `@deepseek-ai/dsh-client-ui-wh-${slug}`
const tabOrder = 40

const hostDir = join(ROOT, 'packages', slug, `${slug}-host`)
const clientDir = join(ROOT, 'packages', 'client', `ui-wh-${slug}`)
if (existsSync(hostDir) || existsSync(clientDir)) {
  console.error(`Error: plugin "${slug}" already exists.`); process.exit(1)
}

console.log(`\nScaffolding: ${slug}\n  Host:   packages/${slug}/${slug}-host\n  Client: packages/client/ui-wh-${slug}\n`)

// ── helpers ──────────────────────────────────────────────────────────────────
function w(rel, content) {
  const abs = join(ROOT, rel); mkdirSync(dirname(abs), { recursive: true })
  writeFileSync(abs, content); console.log(`  + ${rel}`)
}
function patchJson(rel, fn) {
  const abs = join(ROOT, rel); const d = JSON.parse(readFileSync(abs, 'utf8'))
  fn(d); writeFileSync(abs, JSON.stringify(d, null, 2) + '\n'); console.log(`  ~ ${rel}`)
}
function patchText(rel, anchor, add, check) {
  const abs = join(ROOT, rel); let t = readFileSync(abs, 'utf8')
  if (check && t.includes(check)) { console.log(`  = ${rel} (already wired)`); return }
  if (!t.includes(anchor)) { console.error(`  ! anchor not found in ${rel}`); process.exit(1) }
  t = t.replace(anchor, anchor + '\n' + add)
  writeFileSync(abs, t); console.log(`  ~ ${rel}`)
}

// ── 1. Host package.json ─────────────────────────────────────────────────────
w(`packages/${slug}/${slug}-host/package.json`, JSON.stringify({
  name: hostPkg,
  description: `${Pascal} plugin (generated by dsh-new-plugin)`,
  version: '0.1.0-rc.7',
  publishConfig: { access: 'public' },
  repository: { type: 'git', url: 'git+https://github.com/deepseek-ai/deepseek-harness.git', directory: `packages/${slug}/${slug}-host` },
  type: 'module',
  main: 'lib/index.js',
  types: 'lib/types/index.d.ts',
  exports: {
    '.': { types: './lib/types/index.d.ts', default: './lib/index.js' },
    './invariant': { types: './lib/types/invariant.d.ts', default: './lib/invariant.js' },
    './types': { types: './lib/types/types.d.ts', default: './lib/types/types.js' },
    './typert': { types: './lib/typert.host.d.ts', default: './lib/typert.host.js' },
    './remote': { types: './lib/typert.remote-client.d.ts', default: './lib/typert.remote-client.js' },
    './src/*': './src/*',
    './package.json': './package.json',
  },
  files: [
    'lib/index.js', 'lib/invariant.js', 'lib/types/**/*.js', 'lib/types/**/*.d.ts',
    'lib/typert.host.js', 'lib/typert.host.d.ts',
    'lib/typert.remote-client.js', 'lib/typert.remote-client.d.ts',
  ],
  license: 'MIT',
  peerDependencies: {
    '@deepseek-ai/dsh-invariants': 'workspace:^',
    '@deepseek-ai/dsh-storage-domain': 'workspace:^',
    '@deepseek-ai/dsh-typert-protocol': 'workspace:^',
    '@deepseek-ai/cordis': 'workspace:^',
  },
  dependencies: { zod: '^4.4.3' },
  devDependencies: {
    '@deepseek-ai/dsh-invariants': 'workspace:^',
    '@deepseek-ai/dsh-storage': 'workspace:^',
    '@deepseek-ai/dsh-storage-domain': 'workspace:^',
    '@deepseek-ai/dsh-storage-json': 'workspace:^',
    '@deepseek-ai/dsh-typert-protocol': 'workspace:^',
    '@deepseek-ai/cordis': 'workspace:^',
  },
}, null, 2) + '\n')

// ── 2. Host tsconfig.json ────────────────────────────────────────────────────
w(`packages/${slug}/${slug}-host/tsconfig.json`, JSON.stringify({
  extends: '../../../tsconfig.base.json',
  compilerOptions: { rootDir: 'src', outDir: 'lib/types' },
  include: ['src'],
  references: [
    { path: '../../../vendor/cordis' },
    { path: '../../../vendor/schemastery' },
    { path: '../../storage/storage' },
    { path: '../../storage/storage-domain' },
    { path: '../../typert/protocol' },
    { path: '../../runtime-diagnostics/invariants' },
  ],
}, null, 2) + '\n')

// ── 3. Host src/types.ts ─────────────────────────────────────────────────────
w(`packages/${slug}/${slug}-host/src/types.ts`, `/**
 * Public request, value, and failure vocabulary for the ${Pascal} Remote.
 * @module ${hostPkg}/types
 */

export interface ${Pascal}Item {
  readonly id: string
  readonly name: string
  readonly enabled: boolean
  readonly createdAt: string
  readonly updatedAt: string
}

export interface ${Pascal}ItemInput {
  readonly id: string
  readonly name: string
  readonly enabled?: boolean
}

/** Read all items. */
export interface ${Pascal}ListRequest { readonly _?: never }
export interface ${Pascal}ListValue { readonly items: readonly ${Pascal}Item[] }

/** Create or replace one item. */
export interface ${Pascal}SaveRequest { readonly input: ${Pascal}ItemInput }
export type ${Pascal}SaveValue = ${Pascal}Item

/** Delete one item by id. */
export interface ${Pascal}DeleteRequest { readonly id: string }
export interface ${Pascal}DeleteValue { readonly deleted: boolean }

/** Concrete business failures. */
export type ${Pascal}Failure =
  | { readonly code: 'invalid-input'; readonly message: string }
  | { readonly code: 'not-found'; readonly message: string }

export interface ${Pascal}Success<T> { readonly ok: true; readonly value: T }
export interface ${Pascal}Rejected<E extends ${Pascal}Failure> { readonly ok: false; readonly error: E }

export type ${Pascal}ListResult = ${Pascal}Success<${Pascal}ListValue> | ${Pascal}Rejected<${Pascal}Failure>
export type ${Pascal}SaveResult = ${Pascal}Success<${Pascal}SaveValue> | ${Pascal}Rejected<${Pascal}Failure>
export type ${Pascal}DeleteResult = ${Pascal}Success<${Pascal}DeleteValue> | ${Pascal}Rejected<${Pascal}Failure>
`)

// ── 4. Host src/spec.ts ──────────────────────────────────────────────────────
w(`packages/${slug}/${slug}-host/src/spec.ts`, `import { z } from 'zod'
import { defineDomain, domainTable } from '@deepseek-ai/dsh-storage-domain'

/**
 * Storage-domain spec for the ${camel} plugin.
 * Table names must match /^[a-z][a-z0-9_]*$/ (lowercase, digits, underscore).
 */
export const itemRecord = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  enabled: z.boolean().default(true),
  createdAt: z.string(),
  updatedAt: z.string(),
})

export type ItemRecord = z.infer<typeof itemRecord>

export const ${camel}DomainSpec = defineDomain({
  name: '${slug.replace(/-/g, '_')}',
  version: 1,
  tables: {
    items: domainTable<ItemRecord['id'], ItemRecord>(itemRecord),
  },
})
`)

// ── 5. Host src/index.ts ─────────────────────────────────────────────────────
w(`packages/${slug}/${slug}-host/src/index.ts`, `/**
 * ${Pascal} Host service — generated skeleton.
 * @module ${hostPkg}
 */

import { Service } from '@deepseek-ai/cordis'
import { TypertRemoteService, Remote } from '@deepseek-ai/dsh-typert-protocol'
import type { KvTable } from '@deepseek-ai/dsh-storage-domain'
import { ${camel}DomainSpec, type ItemRecord } from './spec.ts'
import type {
  ${Pascal}DeleteRequest, ${Pascal}DeleteResult, ${Pascal}DeleteValue,
  ${Pascal}Failure,
  ${Pascal}Item,
  ${Pascal}ListRequest, ${Pascal}ListResult, ${Pascal}ListValue,
  ${Pascal}SaveRequest, ${Pascal}SaveResult,
} from './types.ts'

declare module '@deepseek-ai/cordis' {
  interface Context { ${camel}: ${Pascal}Service }
}

function success<T>(value: T): { ok: true; value: T } { return { ok: true, value } }
function rejected<E extends ${Pascal}Failure>(error: E): { ok: false; error: E } { return { ok: false, error } }

/** The ${Pascal} store, exposed as Remote \`${camel}\`. */
export class ${Pascal}Service extends TypertRemoteService {
  static inject = ['storageDomain']

  private table: KvTable<string, ItemRecord> | null = null

  constructor(ctx: import('@deepseek-ai/cordis').Context) {
    super(ctx, '${camel}')
  }

  protected async [Service.init](): Promise<void> {
    const domain = await this.ctx.storageDomain.open(${camel}DomainSpec)
    this.ctx.effect(() => () => void domain.close(), '${slug}.domainClose')
    this.table = domain.table('items')
  }

  @Remote('listItems')
  async listItems(_request: ${Pascal}ListRequest): Promise<${Pascal}ListResult> {
    const table = this.requireTable()
    const items: ${Pascal}Item[] = [...table.entries()]
      .map(([, r]) => toItem(r))
      .sort((a, b) => b.createdAt.localeCompare(a.createdAt))
    const value: ${Pascal}ListValue = { items }
    return success(value)
  }

  @Remote('saveItem')
  async saveItem(request: ${Pascal}SaveRequest): Promise<${Pascal}SaveResult> {
    const input = request.input
    if (!/^[\\w-]+$/.test(input.id))
      return rejected({ code: 'invalid-input', message: 'id must be alphanumeric, dash, or underscore' })
    if (input.name.trim().length === 0)
      return rejected({ code: 'invalid-input', message: 'name is required' })
    const table = this.requireTable()
    const now = new Date().toISOString()
    const existing = table.get(input.id)
    const record: ItemRecord = {
      id: input.id,
      name: input.name.trim(),
      enabled: input.enabled ?? existing?.enabled ?? true,
      createdAt: existing?.createdAt ?? now,
      updatedAt: now,
    }
    await table.put(record.id, record)
    return success(toItem(record))
  }

  @Remote('deleteItem')
  async deleteItem(request: ${Pascal}DeleteRequest): Promise<${Pascal}DeleteResult> {
    const table = this.requireTable()
    const deleted = await table.delete(request.id)
    const value: ${Pascal}DeleteValue = { deleted }
    return success(value)
  }

  private requireTable(): KvTable<string, ItemRecord> {
    if (this.table === null) throw new Error('${Pascal}Service not initialized')
    return this.table
  }
}

function toItem(r: ItemRecord): ${Pascal}Item {
  return { id: r.id, name: r.name, enabled: r.enabled, createdAt: r.createdAt, updatedAt: r.updatedAt }
}

export default ${Pascal}Service
`)

// ── 6. Host src/invariant.ts ─────────────────────────────────────────────────
w(`packages/${slug}/${slug}-host/src/invariant.ts`, `/**
 * Package-owned invariant companion for \`${hostPkg}\`.
 * @module ${hostPkg}/invariant
 */

import type { Context } from '@deepseek-ai/cordis'
import type { InvariantInstaller } from '@deepseek-ai/dsh-invariants'

const PACKAGE_NAME = '${hostPkg}'
export const name = '${slug}-host-invariant'
export const inject = ['invariants']
const install: InvariantInstaller = () => {}
export const apply = (ctx: Context): Promise<() => void> =>
  Promise.resolve(ctx.invariants.register(PACKAGE_NAME, install))
`)

// ── 7. Client package.json ───────────────────────────────────────────────────
w(`packages/client/ui-wh-${slug}/package.json`, JSON.stringify({
  name: clientPkg,
  description: `${Pascal} settings tab (generated by dsh-new-plugin)`,
  version: '0.1.0-rc.7',
  publishConfig: { access: 'public' },
  repository: { type: 'git', url: 'git+https://github.com/deepseek-ai/deepseek-harness.git', directory: `packages/client/ui-wh-${slug}` },
  type: 'module',
  main: 'lib/index.js',
  types: 'lib/types/index.d.ts',
  exports: {
    '.': { types: './lib/types/index.d.ts', default: './lib/index.js' },
    './invariant': { types: './lib/types/invariant.d.ts', default: './lib/invariant.js' },
    './client': { types: './lib/types/client/index.d.ts', default: './lib/client.js' },
    './src/*': './src/*',
    './package.json': './package.json',
  },
  dsh: { client: { platform: 'web', inject: ['@deepseek-ai/dsh-client-ui-slots'] } },
  scripts: { bundle: 'tsdown' },
  dependencies: {
    '@deepseek-ai/dsh-client-runtime': 'workspace:^',
    '@deepseek-ai/dsh-client-ui-slots': 'workspace:^',
    '@deepseek-ai/dsh-client-ui-primitives': 'workspace:^',
    [hostPkg]: 'workspace:^',
    react: '^18.2.0',
  },
  peerDependencies: {
    '@deepseek-ai/cordis': 'workspace:^',
    '@deepseek-ai/dsh-client-locale': 'workspace:^',
  },
  devDependencies: {
    '@deepseek-ai/cordis': 'workspace:^',
    '@deepseek-ai/dsh-invariants': 'workspace:^',
    [hostPkg]: 'workspace:^',
    '@deepseek-ai/dsh-client-test-runtime': 'workspace:^',
    '@testing-library/react': '^16.1.0',
    '@deepseek-ai/dsh-client-locale': 'workspace:^',
    '@types/react': '~18.3.1',
  },
  files: ['lib/index.js', 'lib/invariant.js', 'lib/client.js', 'lib/types/**/*.d.ts'],
  license: 'MIT',
}, null, 2) + '\n')

// ── 8. Client tsconfig.json ──────────────────────────────────────────────────
w(`packages/client/ui-wh-${slug}/tsconfig.json`, JSON.stringify({
  extends: '../../../tsconfig.base.client.json',
  compilerOptions: { rootDir: 'src', outDir: 'lib/types' },
  include: ['src'],
  references: [
    { path: '../../../vendor/cordis' },
    { path: '../locale' },
    { path: '../runtime' },
    { path: '../ui-primitives' },
    { path: '../ui-slots' },
    { path: '../ui-settings' },
    { path: '../web-react' },
    { path: '../../api/remotes/tsconfig.client.json' },
    { path: `../../${slug}/${slug}-host` },
    { path: '../../runtime-diagnostics/invariants' },
  ],
}, null, 2) + '\n')

// ── 9. Client tsdown.config.ts ───────────────────────────────────────────────
w(`packages/client/ui-wh-${slug}/tsdown.config.ts`,
`import { clientBundle } from '../tsdown.client.ts'
export default clientBundle('${clientPkg}', ['lib/types/index.js', 'lib/types/invariant.js'])
`)

// ── 10. Client css-modules.d.ts ──────────────────────────────────────────────
w(`packages/client/ui-wh-${slug}/src/css-modules.d.ts`,
`declare module '*.module.css' {
  const classes: Readonly<Record<string, string>>
  export default classes
}
`)

// ── 11. Client src/client/locales.ts ─────────────────────────────────────────
w(`packages/client/ui-wh-${slug}/src/client/locales.ts`,
`export type ${Pascal}Key =
  | 'tab' | 'title' | 'action.add' | 'action.edit' | 'action.save'
  | 'action.cancel' | 'action.close' | 'action.delete' | 'field.name'
  | 'field.enabled' | 'list.empty' | 'delete.title' | 'delete.confirm'

export const zh: Record<${Pascal}Key, string> = {
  tab: '${Pascal}',
  title: '${Pascal}',
  'action.add': '添加',
  'action.edit': '编辑',
  'action.save': '保存',
  'action.cancel': '取消',
  'action.close': '关闭',
  'action.delete': '删除',
  'field.name': '名称',
  'field.enabled': '启用',
  'list.empty': '暂无数据',
  'delete.title': '确认删除',
  'delete.confirm': '确定删除此项目？',
}

export const en: Record<${Pascal}Key, string> = {
  tab: '${Pascal}',
  title: '${Pascal}',
  'action.add': 'Add',
  'action.edit': 'Edit',
  'action.save': 'Save',
  'action.cancel': 'Cancel',
  'action.close': 'Close',
  'action.delete': 'Delete',
  'field.name': 'Name',
  'field.enabled': 'Enabled',
  'list.empty': 'No items yet',
  'delete.title': 'Confirm Delete',
  'delete.confirm': 'Delete this item?',
}
`)

// ── 12. Client src/client/${Pascal}.tsx ──────────────────────────────────────
w(`packages/client/ui-wh-${slug}/src/client/${Pascal}.tsx`,
`import { useEffect, useState } from 'react'
import { Button, Input, Modal } from '@deepseek-ai/dsh-client-ui-primitives'
import type {
  ${Pascal}DeleteRequest, ${Pascal}DeleteResult,
  ${Pascal}Item, ${Pascal}ItemInput,
  ${Pascal}ListRequest, ${Pascal}ListResult,
  ${Pascal}SaveRequest, ${Pascal}SaveResult,
} from '${hostPkg}/types'
import type { RemoteResult } from '@deepseek-ai/dsh-typert-protocol'
import css from './${Pascal}.module.css'
import type { ${Pascal}Key } from './locales.ts'

export interface ${Pascal}ConfigProps {
  t: (key: ${Pascal}Key) => string
  listItems: (_request: ${Pascal}ListRequest) => Promise<RemoteResult<${Pascal}ListResult>>
  saveItem: (request: ${Pascal}SaveRequest) => Promise<RemoteResult<${Pascal}SaveResult>>
  deleteItem: (request: ${Pascal}DeleteRequest) => Promise<RemoteResult<${Pascal}DeleteResult>>
}

export type ${Pascal}Injected = Omit<${Pascal}ConfigProps, 't'>

export function ${Pascal}Config({ t, listItems, saveItem, deleteItem }: ${Pascal}ConfigProps) {
  const [items, setItems] = useState<${Pascal}Item[]>([])
  const [modalOpen, setModalOpen] = useState(false)
  const [editing, setEditing] = useState<${Pascal}Item | null>(null)
  const [name, setName] = useState('')
  const [enabled, setEnabled] = useState(true)
  const [deleteTarget, setDeleteTarget] = useState<${Pascal}Item | null>(null)

  const refresh = async () => {
    const r = await listItems({})
    if (r.ok && r.value.ok) setItems([...r.value.value.items])
  }
  useEffect(() => { void refresh() }, [])

  const openAdd = () => { setEditing(null); setName(''); setEnabled(true); setModalOpen(true) }
  const openEdit = (item: ${Pascal}Item) => { setEditing(item); setName(item.name); setEnabled(item.enabled); setModalOpen(true) }
  const closeModal = () => { setModalOpen(false); setEditing(null) }

  const handleSave = async () => {
    if (name.trim().length === 0) return
    const input: ${Pascal}ItemInput = {
      id: editing?.id ?? crypto.randomUUID(),
      name: name.trim(),
      enabled,
    }
    const r = await saveItem({ input })
    if (r.ok && r.value.ok) { closeModal(); await refresh() }
  }

  const confirmDelete = async () => {
    if (deleteTarget === null) return
    await deleteItem({ id: deleteTarget.id })
    setDeleteTarget(null)
    await refresh()
  }

  return (
    <div className={css.panel}>
      <div className={css.panelHeader}>
        <h3>{t('title')}</h3>
        <Button variant="outline" size="sm" onClick={openAdd}>{t('action.add')}</Button>
      </div>
      <ul className={css.list}>
        {items.map(item => (
          <li key={item.id} className={css.item}>
            <span>{item.name}</span>
            <span className={item.enabled ? css.on : css.off}>{item.enabled ? '●' : '○'}</span>
            <Button variant="ghost" size="sm" onClick={() => openEdit(item)}>{t('action.edit')}</Button>
            <Button variant="ghost" size="sm" onClick={() => setDeleteTarget(item)}>{t('action.delete')}</Button>
          </li>
        ))}
        {items.length === 0 && <li className={css.empty}>{t('list.empty')}</li>}
      </ul>

      <Modal open={modalOpen} onClose={closeModal} title={editing ? t('action.edit') : t('action.add')}
        closeLabel={t('action.close')}
        footer={(<><Button variant="ghost" onClick={closeModal}>{t('action.cancel')}</Button>
          <Button variant="primary" onClick={handleSave}>{t('action.save')}</Button></>)}>
        <label className={css.field}>
          <span>{t('field.name')}</span>
          <Input value={name} onChange={e => setName(e.target.value)} />
        </label>
      </Modal>

      <Modal open={deleteTarget !== null} onClose={() => setDeleteTarget(null)} title={t('delete.title')}
        closeLabel={t('action.close')}
        footer={(<><Button variant="ghost" onClick={() => setDeleteTarget(null)}>{t('action.cancel')}</Button>
          <Button variant="primary" onClick={confirmDelete}>{t('action.delete')}</Button></>)}>
        <p>{t('delete.confirm')}</p>
      </Modal>
    </div>
  )
}
`)

// ── 13. Client CSS module ────────────────────────────────────────────────────
w(`packages/client/ui-wh-${slug}/src/client/${Pascal}.module.css`,
`.panel { padding: 16px; }
.panelHeader { display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; }
.list { list-style: none; padding: 0; margin: 0; }
.item { display: flex; align-items: center; gap: 8px; padding: 8px 0; border-bottom: 1px solid var(--border, #eee); }
.empty { color: #999; padding: 16px 0; }
.on { color: #22c55e; }
.off { color: #9ca3af; }
.field { display: flex; flex-direction: column; gap: 4px; }
`)

// ── 14. Client src/client/index.ts ───────────────────────────────────────────
w(`packages/client/ui-wh-${slug}/src/client/index.ts`,
`import type { ClientContext } from '@deepseek-ai/dsh-client-runtime/client'
import type { InjectFace, PropsLocale, PropsRuntime } from '@deepseek-ai/dsh-client-ui-slots'
import type {} from '@deepseek-ai/dsh-client-ui-settings/client'
import type {} from '@deepseek-ai/dsh-api-remotes/client'
import type {} from '@deepseek-ai/dsh-client-locale/client'
import { ${Pascal}Config } from './${Pascal}.tsx'
import type { ${Pascal}Injected } from './${Pascal}.tsx'
import { en, zh, type ${Pascal}Key } from './locales.ts'

declare module '@deepseek-ai/dsh-client-ui-slots' {
  interface LocaleNamespaceMap { wh${Pascal}: ${Pascal}Key }
}
const NS = 'wh${Pascal}'
export const inject = ['slots', 'locale', 'remote', 'remote.${camel}']

export type ${Pascal}Props =
  PropsRuntime<'settings.plugins.tab'>
  & PropsLocale<'wh${Pascal}'>
  & InjectFace<${Pascal}Injected>

export function apply(ctx: ClientContext): void {
  ctx.effect(() => ctx.locale.register(NS, { zh, en }), 'ui-wh-${slug}: dictionaries')
  const t = ctx.locale.bind(NS)
  const injected = (): ${Pascal}Injected => ({
    listItems: request => ctx.remote.${camel}.listItems(request),
    saveItem: request => ctx.remote.${camel}.saveItem(request),
    deleteItem: request => ctx.remote.${camel}.deleteItem(request),
  })
  ctx.slots.inject('settings.plugins.tab', () => ctx.slots.register({
    name: 'settings.plugins.tab',
    id: 'wh-${slug}',
    order: ${tabOrder},
    label: () => t('tab'),
    locale: NS,
    inject: injected,
  }, ${Pascal}Config))
}
`)

// ── 15. Client src/index.ts (loader entry) ───────────────────────────────────
// NOTE: keep the main entry a deliberate no-op (pve pattern). If it re-exports
// ./client/index.ts, the main-face tsdown build pulls the UI tree into the
// main entry and fails resolving the CSS module. The UI lives in the separate
// client face (src/client/index.ts) consumed via the /client subpath.
w(`packages/client/ui-wh-${slug}/src/index.ts`,
`/**
 * ${Pascal} client, main entry.
 *
 * Deliberately empty Host body: the ${Pascal} service lives in the separate
 * \`${hostPkg}\` package. The browser half renders the settings UI over
 * \`ctx.remote.${camel}\` via the client face (\`./client/index.ts\`).
 */
export function apply(): void {}
`)

// ── 16. Client src/invariant.ts ──────────────────────────────────────────────
w(`packages/client/ui-wh-${slug}/src/invariant.ts`,
`/** No runtime invariant for the ${Pascal} client UI. */
export const name = 'ui-wh-${slug}-invariant'
export const inject = ['invariants']
export const apply = (): Promise<() => void> => Promise.resolve(() => {})
`)

// ── 17. WIRE: tsconfig.host.json ─────────────────────────────────────────────
patchText('tsconfig.host.json',
  `    { "path": "./packages/pve/pve-host" },`,
  `    { "path": "./packages/${slug}/${slug}-host" },`,
  `packages/${slug}/${slug}-host`)

// ── 18. WIRE: tsconfig.client.json ──────────────────────────────────────────
patchText('tsconfig.client.json',
  `    { "path": "./packages/client/ui-wh-pve" },`,
  `    { "path": "./packages/client/ui-wh-${slug}" },`,
  `packages/client/ui-wh-${slug}`)

// ── 19. WIRE: api-remotes package.json (peer + dev deps) ────────────────────
patchJson('packages/api/remotes/package.json', d => {
  d.peerDependencies[hostPkg] = 'workspace:^'
  d.devDependencies[hostPkg] = 'workspace:^'
})

// ── 20/21. WIRE: api-remotes tsconfig.{host,client}.json ────────────────────
// Robust approach: insert a new reference as the LAST entry of the references
// array via regex, so comma placement is always correct regardless of whether
// pve-host is currently last. Skips if already wired.
for (const rel of ['packages/api/remotes/tsconfig.host.json', 'packages/api/remotes/tsconfig.client.json']) {
  const abs = join(ROOT, rel)
  let t = readFileSync(abs, 'utf8')
  const check = `"../../${slug}/${slug}-host"`
  if (t.includes(check)) { console.log(`  = ${rel} (already wired)`); continue }
  const refBlock = new RegExp(`("references"\\s*:\\s*\\[)([\\s\\S]*?)(\\n\\s*\\])`)
  if (!refBlock.test(t)) { console.error(`  ! references array not found in ${rel}`); process.exit(1) }
  t = t.replace(refBlock, (m, open, body, close) => {
    // if body has a trailing `},` without a following entry, trim the comma
    const cleaned = body.replace(/},\s*$/, '}')
    return `${open}${cleaned},\n    {\n      "path": "../../${slug}/${slug}-host"\n    }${close}`
  })
  writeFileSync(abs, t); console.log(`  ~ ${rel}`)
}

// ── 22. WIRE: api-remotes src/client/index.ts ───────────────────────────────
{
  const rel = 'packages/api/remotes/src/client/index.ts'
  const abs = join(ROOT, rel)
  let rt = readFileSync(abs, 'utf8')
  const importLine = `import ${camel}Remote from '${hostPkg}/remote'`
  const typeLine = `export type {} from '${hostPkg}/remote'`
  const contribLine = `      commandsRemote, goalsRemote, dynamicRemote, pluginInventoryRemote, messageFeedbackRemote, dingtalkRemote, pveRemote, ${camel}Remote,`
  const check = `${hostPkg}/remote`
  if (rt.includes(check)) {
    console.log(`  = ${rel} (already wired)`)
  } else {
    // 1) insert side-effect import right after the pveRemote import line
    rt = rt.replace(/import pveRemote from '@deepseek-ai\/dsh-pve-host\/remote'\n/, (m) => `${m}${importLine}\n`)
    // 2) insert type-only re-export right after the pve type-line
    rt = rt.replace(/export type \{\} from '@deepseek-ai\/dsh-pve-host\/remote'\n/, (m) => `${m}${typeLine}\n`)
    // 3) append the mount contribution to the apply() array
    rt = rt.replace(/commandsRemote, goalsRemote, dynamicRemote, pluginInventoryRemote, messageFeedbackRemote, dingtalkRemote, pveRemote,/, (m) => `${m} ${camel}Remote,`)
    writeFileSync(abs, rt)
    console.log(`  ~ ${rel}`)
  }
}

// ── 23. WIRE: web-app cordis.patch.yml (host + client) ──────────────────────
// NOTE: patchText prepends `anchor + '\n'`, so `add` must contain ONLY the new
// lines (do NOT repeat the anchor, or pve-host gets duplicated).
patchText('packages/bundle/web-app/cordis.patch.yml',
  `    - id: pve-host\n      name: '@deepseek-ai/dsh-pve-host'\n`,
  `    - id: ${slug}-host\n      name: '${hostPkg}'\n`,
  `${slug}-host`)
patchText('packages/bundle/web-app/cordis.patch.yml',
  `    - id: ui-wh-pve\n      name: '@deepseek-ai/dsh-client-ui-wh-pve'\n`,
  `    - id: ui-wh-${slug}\n      name: '${clientPkg}'\n`,
  `ui-wh-${slug}`)

// ── 24. WIRE: web-app package.json deps ──────────────────────────────────────
patchJson('packages/bundle/web-app/package.json', d => {
  d.dependencies[hostPkg] = 'workspace:^'
  d.dependencies[clientPkg] = 'workspace:^'
})

console.log(`\n✅ Done. Next steps:\n  pnpm install\n  pnpm run build:lib:host\n  npx tsdown --env.DSH_BUILD_FACE client\n  pnpm run build:lib:client\n`)
